import z from "zod";

export const seoContentSchema = z.object({
  title: z
    .string()
    .describe("SEO-optimized product title generated by the model."),
  description: z
    .string()
    .describe("SEO-optimized and engaging product description."),
  tags: z
    .array(z.string())
    .describe("Relevant SEO keyword tags, 5 to 10 items."),
  seoScoreBefore: z
    .number()
    .min(0)
    .max(100)
    .describe(
      "Estimated SEO score (0-100) of the original name and description provided by the user."
    ),
  seoScoreNow: z
    .number()
    .min(80)
    .max(100)
    .describe(
      "SEO score of the optimized content generated by the LLM. Should always be above 80."
    ),
});
